name: Build Docker Image - CI

on:
  push:
    branches: [ "main" ]


jobs:
  job-build:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: LuizHenrique78
            password: ${{ secrets.API_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            platforms: linux/amd64
            push: true
            tags: teste
            build-args: |
              "API_TOKEN=${{ secrets.API_TOKEN }}"
              "AWS_DEFAULT_REGION=${{env.REGION}}"
              "AWS_ACCESS_KEY_ID=${{secrets.ACESSKEY}}"
              "AWS_SECRET_ACCESS_KEY=${{secrets.SECRETKEY}}"
