name: Run python CLI

on:
  workflow_run:
    workflows: ["Build Docker Image - CI"]
    types:
      - completed

jobs:
  job-run:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Import environment variables from a file
        id: import-env
        shell: bash
        run: cat version.env >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.API_TOKEN }}

      # Carregar imagem docker 
      - name: Get image information
        id: inspect-image
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/luizhenrique78/robot-teste:teste
      
      - name: Verify files
        run: docker run -p 80:80 ghcr.io/luizhenrique78/robot-teste:teste ls
          
      - name: run robot
        run: docker run ghcr.io/luizhenrique78/robot-teste:teste robot -d ./logs tests/teste.robot